export interface IParty {
    _id?: string; // MongoDB ObjectId, optional as it's generated by the DB
    MATIEC: string; // Mã tiệc
    TENCR: string; // Tên chú rể
    TENCD: string; // Tên cô dâu
    SDT: string; // Số điện thoại
    NGAYDAI: string; // Ngày đãi (định dạng ISO string hoặc string tùy theo backend trả về)
    CA: string; // Ca
    MASANH: string; // Mã sảnh
    TIENCOC: number; // Tiền cọc
    SOLUONGBAN: number; // Số lượng bàn
    SOBANDT: number; // Số bàn dự trữ
    // status: string; // Trạng thái - Sẽ cần xem xét lại nếu backend có trường này hoặc logic xử lý riêng
    // Các trường cũ có thể được giữ lại hoặc ánh xạ nếu cần thiết cho UI hiện tại
    // Ví dụ, nếu UI vẫn dùng 'groom', 'bride', etc., chúng ta cần ánh xạ trong component
    // Tạm thời giữ lại các trường cũ để giảm thiểu thay đổi ở component, sẽ ánh xạ sau
    id?: number; // Giữ lại id cũ nếu cần cho logic hiện tại, hoặc sẽ loại bỏ
    groom: string; // Sẽ được map từ TENCR
    bride: string; // Sẽ được map từ TENCD
    phone: string; // Sẽ được map từ SDT
    date: string; // Sẽ được map từ NGAYDAI
    shift: string; // Sẽ được map từ CA
    hall: string; // Sẽ được map từ MASANH
    deposit: number; // Sẽ được map từ TIENCOC
    tables: number; // Sẽ được map từ SOLUONGBAN
    reserveTables: number; // Sẽ được map từ SOBANDT
    status?: string; // Trạng thái, có thể backend không có trường này trực tiếp
}